name: uts
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  intl: ^0.18.1
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Mortend
      fonts:
        - asset: fonts/Mortend-Bold.ttf